"""generate sent_at for messages in db

Revision ID: 157449c23945
Revises: cabae5338e39
Create Date: 2025-12-10 09:16:40.533663

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "157449c23945"
down_revision: Union[str, Sequence[str], None] = "cabae5338e39"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "messages",
        "sent_at",
        existing_type=sa.DateTime(),
        server_default=sa.text("NOW()"),
        existing_nullable=False,
    )  ### end Alembic commands ###
    pass


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "messages",
        "sent_at",
        existing_type=sa.DateTime(),
        server_default=None,
        existing_nullable=False,
    )
    pass
    # ### end Alembic commands ###
