"""generate uuid in db v2

Revision ID: cabae5338e39
Revises: 2d2f60f5b291
Create Date: 2025-12-10 08:55:55.685536

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "cabae5338e39"
down_revision: Union[str, Sequence[str], None] = "2d2f60f5b291"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "messages",
        "id",
        existing_type=sa.dialects.postgresql.UUID(),
        server_default=sa.text("gen_random_uuid()"),
        existing_nullable=False,
    )
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust!
    op.alter_column(
        "messages",
        "id",
        existing_type=sa.dialects.postgresql.UUID(),
        server_default=None,
        existing_nullable=False,
    )
    pass
    # ### end Alembic commands ###
