"""created time for groups and members

Revision ID: d59149176e10
Revises: 8d394e067d29
Create Date: 2025-12-18 19:56:24.966315

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "d59149176e10"
down_revision: Union[str, Sequence[str], None] = "8d394e067d29"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "group_chats",
        "created_at",
        existing_type=sa.DateTime(),
        server_default=sa.text("NOW()"),
        existing_nullable=False,
    )
    op.alter_column(
        "group_members",
        "joined_at",
        existing_type=sa.DateTime(),
        server_default=sa.text("NOW()"),
        existing_nullable=False,
    )
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "group_chats",
        "created_at",
        existing_type=sa.DateTime(),
        server_default=None,
        existing_nullable=False,
    )
    op.alter_column(
        "group_members",
        "joined_at",
        existing_type=sa.DateTime(),
        server_default=None,
        existing_nullable=False,
    )
    pass
    # ### end Alembic commands ###
