"""add salt

Revision ID: dad579d1ebc0
Revises: d59149176e10
Create Date: 2025-12-30 20:37:26.731188

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "dad579d1ebc0"
down_revision: Union[str, Sequence[str], None] = "d59149176e10"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("user_accounts", sa.Column("salt", sa.Text(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("user_accounts", "salt")
    # ### end Alembic commands ###
