"""create all tables

Revision ID: e48fc5f87e76
Revises: e0e0abd15935
Create Date: 2025-12-05 13:27:44.786321

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "e48fc5f87e76"
down_revision: Union[str, Sequence[str], None] = "e0e0abd15935"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "group",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(length=50), nullable=False),
        sa.Column("createdAt", postgresql.TIMESTAMP(), nullable=False),
        sa.Column("deletedAt", postgresql.TIMESTAMP(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "group_member",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("userId", sa.Integer(), nullable=False),
        sa.Column("groupId", sa.Integer(), nullable=False),
        sa.Column(
            "role", sa.Enum("ADMIN", "MEMBER", name="groupmemberrole"), nullable=False
        ),
        sa.Column("joinedAt", postgresql.TIMESTAMP(), nullable=False),
        sa.Column("leftAt", postgresql.TIMESTAMP(), nullable=True),
        sa.ForeignKeyConstraint(
            ["groupId"],
            ["group.id"],
        ),
        sa.ForeignKeyConstraint(
            ["userId"],
            ["user.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "message",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("senderId", sa.Integer(), nullable=False),
        sa.Column("groupId", sa.Integer(), nullable=False),
        sa.Column("content", sa.Text(), nullable=False),
        sa.Column("sentAt", postgresql.TIMESTAMP(), nullable=False),
        sa.Column("deletedAt", postgresql.TIMESTAMP(), nullable=True),
        sa.Column("repliedTo", sa.UUID(), nullable=True),
        sa.ForeignKeyConstraint(
            ["groupId"],
            ["group.id"],
        ),
        sa.ForeignKeyConstraint(
            ["repliedTo"],
            ["message.id"],
        ),
        sa.ForeignKeyConstraint(
            ["senderId"],
            ["user.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "session",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("userId", sa.Integer(), nullable=False),
        sa.Column("token", sa.Text(), nullable=False),
        sa.Column("expiresAt", postgresql.TIMESTAMP(), nullable=False),
        sa.Column("createdAt", postgresql.TIMESTAMP(), nullable=False),
        sa.Column("deletedAt", postgresql.TIMESTAMP(), nullable=True),
        sa.ForeignKeyConstraint(
            ["userId"],
            ["user.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "user_account",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("accountType", sa.String(length=25), nullable=False),
        sa.Column("userId", sa.Integer(), nullable=False),
        sa.Column("username", sa.String(length=25), nullable=False),
        sa.Column("password", sa.Text(), nullable=False),
        sa.ForeignKeyConstraint(
            ["userId"],
            ["user.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "message_status",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("messageId", sa.UUID(), nullable=False),
        sa.Column("userId", sa.Integer(), nullable=False),
        sa.Column("readAt", postgresql.TIMESTAMP(), nullable=True),
        sa.ForeignKeyConstraint(
            ["messageId"],
            ["message.id"],
        ),
        sa.ForeignKeyConstraint(
            ["userId"],
            ["user.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.alter_column("user", "name", existing_type=sa.VARCHAR(), nullable=False)
    op.alter_column(
        "user", "createdAt", existing_type=postgresql.TIMESTAMP(), nullable=False
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "user", "createdAt", existing_type=postgresql.TIMESTAMP(), nullable=True
    )
    op.alter_column("user", "name", existing_type=sa.VARCHAR(), nullable=True)
    op.drop_table("message_status")
    op.drop_table("user_account")
    op.drop_table("session")
    op.drop_table("message")
    op.drop_table("group_member")
    op.drop_table("group")
    # ### end Alembic commands ###
